language: python

python:
    - "3.6"

os: linux

cache:
  pip: true
  directories:
    - $HOME/.cache

addons:
  postgresql: 9.6

env:
  - DB=postgres
  global:
    - LIBXML2_DEB="libxml2-dbg_2.9.1+dfsg1-3ubuntu4.9_amd64.deb"
    - LIBJEMALLOC_DEB="libjemalloc1_3.5.1-2_amd64.deb"
    - LIBPCRE_DEB="libpcre3_8.31-2ubuntu2.3_amd64.deb"
    - OSF_DB_PORT="54321"
    - PGPORT=54321
  jobs:
    - TEST_BUILD="api2"

before_install:
  # cache directories
  - mkdir -p $HOME/.cache/downloads
  - mkdir -p $HOME/.cache/testmon
  - cd $HOME/.cache/downloads

before_script:
  - psql -c 'create database osf_test;' -U postgres

install:
    - cd $TRAVIS_BUILD_DIR
    - cp website/settings/local-travis.py website/settings/local.py
    - cp api/base/settings/local-travis.py api/base/settings/local.py

    - travis_retry pip install invoke
    - travis_retry invoke requirements --dev --addons

after_script:
    # This ensures failed tests are removed from the cache so they can be re-tried.
    - inv remove_failures_from_testmon --db-path=$HOME/.cache/testmon/.testmondata_$TEST_BUILD

script:
    # Testmon will run for PRs, but will be disabled when merging into master or develop
    - export TESTMON=`if [[ "$TRAVIS_PULL_REQUEST_BRANCH" == "" && "$TRAVIS_BRANCH" == "develop" || "$TRAVIS_PULL_REQUEST_BRANCH" == "" && "$TRAVIS_BRANCH" == "master" ]]; then echo ""; else  echo "--testmon"; fi`
    - export TESTMON_DATAFILE=$HOME/.cache/testmon/.testmondata_$TEST_BUILD
    - invoke test_travis_$TEST_BUILD -n 1 $TESTMON

before_cache:
  # kill any running processes
  - kill -9 $POSTGRES_PID
  - kill -9 $ELASTICSEARCH_PID
  - kill -9 $ELASTICSEARCH6_PID

branches:
  except:
    - /^[0-9]/
