name: 'Build ElasticSearch'
description: 'Building and starting the ElasticSearch Service'
inputs:
  ELASTICSEARCH_ARCHIVE:
    description: 'Where ES archive is located'
runs:
  using: "composite"
  steps:
  - id: ES-Step-1
    shell: bash
    run: |
      cd ~/.cache/downloads
      curl -SLO https://artifacts.elastic.co/downloads/elasticsearch/${{ inputs.ELASTICSEARCH_ARCHIVE }}

      mkdir -p /tmp/elasticsearch
      tar -xzf ${{ inputs.ELASTICSEARCH_ARCHIVE }} -C /tmp/elasticsearch --strip-components=1
      echo "ES started..."
