# Generated by Django 3.1.1 on 2021-06-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="block",
            name="check_page_heading",
        ),
        migrations.RemoveConstraint(
            model_name="block",
            name="check_section_heading",
        ),
        migrations.RemoveConstraint(
            model_name="block",
            name="check_file_input",
        ),
        migrations.AlterField(
            model_name="block",
            name="display_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="AKA title",
                max_length=5000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="example_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="AKA example",
                max_length=5000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="help_text",
            field=models.CharField(
                blank=True, default="", help_text="AKA help", max_length=5000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="nav",
            field=models.CharField(blank=True, default="", max_length=5000, null=True),
        ),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(_negated=True, block_type="page-heading"),
                    models.Q(
                        ("block_type", "page-heading"),
                        ("example_text__isnull", True),
                        ("help_text__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="check_page_heading",
            ),
        ),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(_negated=True, block_type="section-heading"),
                    models.Q(
                        ("block_type", "section-heading"),
                        ("example_text__isnull", True),
                        ("help_text__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="check_section_heading",
            ),
        ),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(_negated=True, block_type="file-input"),
                    models.Q(
                        ("block_type", "file-input"),
                        ("display_text__isnull", True),
                        ("example_text__isnull", True),
                        ("help_text__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="check_file_input",
            ),
        ),
    ]
