# Generated by Django 3.1.1 on 2021-06-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210620_1956'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='block',
            name='check_page_heading',
        ),
        migrations.RemoveConstraint(
            model_name='block',
            name='check_section_heading',
        ),
        migrations.RemoveConstraint(
            model_name='block',
            name='check_file_input',
        ),
    ]
