# Generated by Django 3.1.1 on 2021-06-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210611_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='header',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
