# Generated by Django 3.1.1 on 2021-06-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_auto_20210620_1957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="index",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
