# Generated by Django 3.1.1 on 2021-06-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_question_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
