# Generated by Django 3.1.1 on 2021-06-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_page_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('id', 'number')},
        ),
    ]
