# Generated by Django 3.1.1 on 2021-06-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_auto_20210621_0023"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="csv",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
