# Generated by Django 3.1.1 on 2021-06-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_block_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='csv',
            field=models.FileField(null=True, upload_to='csv/'),
        ),
    ]
