# Generated by Django 3.1.1 on 2021-06-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210611_1340'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('page', 'number')},
        ),
    ]
