# Generated by Django 3.1.1 on 2021-06-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_auto_20210621_1212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="csv",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
