# Generated by Django 3.1.1 on 2021-06-12 00:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20210611_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='header',
        ),
        migrations.RemoveField(
            model_name='question',
            name='help',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='display_text',
            field=models.CharField(blank=True, help_text='AKA title', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='example_text',
            field=models.CharField(blank=True, help_text='AKA example', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='help_text',
            field=models.CharField(blank=True, help_text='AKA help', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='format',
            field=models.CharField(blank=True, choices=[('page-heading', 'Page Heading'), ('section-heading', 'Section Heading'), ('subsection-heading', 'Subsection Heading'), ('paragraph', 'Paragraph'), ('question-label', 'Question Label'), ('short-text-input', 'Short Text Input'), ('long-text-input', 'Long Text Input'), ('file-input', 'File Input'), ('contributors-input', 'Contributors Input'), ('single-select-input', 'Single Select Input'), ('multi-select-input', 'Multi-select Input'), ('select-input-option', 'Select Input Option'), ('select-other-option', 'Select Other Option')], max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='Enter as comma separated list', null=True, size=None),
        ),
    ]
