# Generated by Django 3.1.1 on 2021-06-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20210612_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='csv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
