# Generated by Django 3.1.1 on 2021-07-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_user_bulk_contributors_csv"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="guid",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
