# Generated by Django 3.1.1 on 2021-06-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_schema_csv'),
    ]

    operations = [
    ]
