# Generated by Django 3.1.1 on 2021-06-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20210614_1744'),
    ]

    operations = [
    ]
