# Generated by Django 3.1.1 on 2021-06-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20210614_1745'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, format='page-heading'), models.Q(('example_text__isnull', True), ('format', 'page-heading'), ('help_text__isnull', True)), _connector='OR'), name='check_page_heading'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, format='section-heading'), models.Q(('example_text__isnull', True), ('format', 'section-heading'), ('help_text__isnull', True)), _connector='OR'), name='check_section_heading'),
        ),
    ]
