# Generated by Django 3.2.17 on 2024-01-22 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0018_merge_20231218_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprint',
            name='pending_primary_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preprint_pending', to='osf.osfstoragefile'),
        ),
    ]
