# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 14:03
from __future__ import unicode_literals

from django.db import migrations
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retraction',
            name='date_retracted',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True),
        ),
    ]
