# Generated by Django 4.2.13 on 2025-04-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0029_remove_abstractnode_keenio_read_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractnode',
            name='registered_meta',
        ),
        migrations.RemoveField(
            model_name='draftregistration',
            name='registration_metadata',
        ),
    ]
