# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-27 21:07
from __future__ import unicode_literals

import logging
from django.db import migrations

logger = logging.getLogger(__name__)

from osf.migrations.utils.utils import post_migrate_signal


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0161_guardian_direct_fks'),
    ]

    operations = [
        migrations.RunPython(post_migrate_signal, migrations.RunPython.noop),
    ]
