# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-08 15:12
from __future__ import unicode_literals
import logging
from django.db import migrations
logger = logging.getLogger(__file__)

from osf.migrations.utils.utils import forward, backward


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0162_conference_submissions'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
