# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-15 18:42
from __future__ import unicode_literals

import logging

from django.db import migrations
from website.settings import DEBUG_MODE

logger = logging.getLogger(__name__)

from osf.migrations.utils.utils import (
    migrate_draft_registration_metadata,
    clear_draft_registration_responses,
    migrate_registration_registered_meta,
    clear_registration_responses
)

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0192_add_registation_responses_fields'),
    ]

    if DEBUG_MODE:
        operations = [
            migrations.RunPython(migrate_draft_registration_metadata, clear_draft_registration_responses),
            migrations.RunPython(migrate_registration_registered_meta, clear_registration_responses),
        ]
    else:
        operations = []
        logger.info(
            'The automatic migration only runs in DEBUG_MODE. Use management command migrate_registration_responses instead'
        )
