# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-25 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0201_auto_20200225_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osfuser',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='osfuser',
            name='schools',
        ),
    ]
