# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-08 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0209_branded_registries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftregistration',
            name='provider',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='draft_registrations', to='osf.RegistrationProvider'),
        ),
    ]
