# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-09 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from osf.models import RegistrationProvider
from website import settings


def get_default():
    try:
        default_registration_provider = RegistrationProvider.objects.get(_id=settings.REGISTRATION_PROVIDER_DEFAULT__ID)
    except RegistrationProvider.DoesNotExist:
        default_registration_provider = RegistrationProvider(**{
            '_id': settings.REGISTRATION_PROVIDER_DEFAULT__ID,
            'name': 'OSF Registries'
        })
        default_registration_provider.save()

    return default_registration_provider.id


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0209_branded_registries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftregistration',
            name='provider',
            field=models.ForeignKey(default=get_default, on_delete=django.db.models.deletion.CASCADE, related_name='draft_registrations', to='osf.RegistrationProvider'),
            preserve_default=False,
        ),
    ]
