# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-21 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0219_auto_20201020_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftregistration',
            name='machine_state',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='moderation_state',
            field=models.CharField(choices=[('initial', 'Initial'), ('pending', 'Pending'), ('accepted', 'Accepted'),
                                            ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'),
                                            ('pending_embargo', 'Pending_Embargo'), ('embargo', 'Embargo'),
                                            ('pending_embargo_termination', 'Pending_Embargo_Termination'),
                                            ('pending_withdraw_request', 'Pending_Withdraw_Request'),
                                            ('pending_withdraw', 'Pending_Withdraw')], db_index=True, default='initial',
                                   max_length=30),

        ),

    ]
